@startuml
!theme reddress-darkred
skinparam conditionStyle inside
title Алгоритм "12 месяцев"

start
:Дочь и Мачеха: отправить в лес падчерицу;
:Падчерица: искать подснежники;

:Встретить Январь у костра;
:Падчерица: попросить подснежники;

if (Январь может помочь?) then (да)
    :Январь: передать жезл Февралю;
    if (Февраль может помочь?) then (да)
        :Февраль: передать жезл Марту;
        if (Март может помочь?) then (да)
            :Март: передать жезл Апрелю;
            :Апрель: уступает место весне;
            :Вырастить подснежники;
            :Падчерица: собрать цветы;
            :Мачеха забрала цветы;
            :Мачеха едет к королеве;
            
            if (Королева требует цветы?) then (да)
                :Дочь и мачеха: отослать в лес;
                fork
                    :Дочь и мачеха: хамить месяцам;
                    :Дочь и мачеха: замерзнуть в лесу;
                fork again
                    :Падчерица: хорошо себя вести;
                    :Месяцы: наградить Падчерицу;
                end fork
                :Счастливый конец;
            else (нет)
                :Падчерица: вернуться домой;
            endif
        else (нет)
            :Отказ Марта;
            :Падчерица: замёрзнуть в лесу;
        endif
    else (нет)
        :Отказ Февраля;
        :Падчерица: замёрзнуть в лесу;
    endif
else (нет)
    :Отказ Января;
    :Падчерица: замёрзнуть в лесу;
endif

stop
@enduml
