@startuml
!theme reddress-darkred

title "Пошаговое взаимодействие 12 месяцев"
actor "Падчерица" as P
participant "Подснежники" as EB
actor "Мачеха и дочь" as M
participant "Сменить сезон" as EA
actor "Январь" as J
actor "Февраль" as F
actor "Март" as D
actor "Апрель" as A
actor "Королева" as K

M -> P : Отправить в лес
P -> EB **: Искать
EB --[#red]> J : Просить помощи братьев-Месяцев
J -> F : Передать следующему
F -> D : Передать следующему
D -> A : Передать следующему
A -> EA **: Сменить сезон
EA -[#darkred]> EB : Растут
EB -> P : Собрать цветы
P -> M : Отдает цветы Мачехе
M -> K : Несут цветы королеве
K -> K : Требует ещё
K -> M : Отправляет обратно в лес
M --[#red]> J : Требовать подснежники
J -> J : Злится
note over J : Оставляет их ни с чем
J -[#darkred]> M : Отправляет в лес
M -> M : Замерзнуть в лесу
destroy M
note over P : Вежливая и добрая
A -> P : Дарят подарки

@enduml
