@startuml
!theme reddress-darkred

skinparam state {
  BackgroundColor<<Winter>> #darkblue
  BackgroundColor<<Spring_Temporary>> #darkgreen
  BackgroundColor<<Broken>> #red
  BackgroundColor<<Success>> #darkgreen
}

title Жизненный цикл системы "12 месяцев"

state "Зима" as Зима <<Winter>>
state "Весна временная" as Весна <<Spring_Temporary>>

state "Нет цветов" as НетЦветов
state "Цветы выросли" as ЦветыЕсть
state "Цветы собраны" as ЦветыСобраны
state "Цветы замёрзли" as ЦветыЗамёрзли <<Broken>>

state "Персонаж в лесу" as ВЛесу
state "Персонаж у костра" as УКостра
state "Персонаж замёрз" as Замёрз <<Broken>>
state "Персонаж с цветами" as СЦветами <<Success>>

[*] --> Зима

Зима --> Весна : Апрель: сменить\n(через Янв→Фев→Март)
Весна --> Зима : цветы собраны\nили время вышло

Зима --> НетЦветов : подснежники под снегом
Весна --> ЦветыЕсть : вырастают подснежники

ЦветыЕсть --> ЦветыСобраны : Падчерица собирает
ЦветыЕсть --> ЦветыЗамёрзли : возврат зимы

[*] --> ВЛесу : отправлен(а)
ВЛесу --> УКостра : найти костёр
УКостра --> Замёрз : грубость
УКостра --> СЦветами : вежливость + получить цветы
СЦветами --> [*] : вернуться домой
Замёрз --> [*] : погибнуть

ЦветыСобраны --> СЦветами : передать цветы
ЦветыЗамёрзли --> Замёрз : персонаж без цветов

note right of Весна
  **Временная весна**
  Создаётся только для
  появления подснежников
end note

note bottom of УКостра
  **Встреча с месяцами**
  Январь, Февраль, Март, Апрель
  сидят у костра
end note

@enduml
